import { DashboardCopy, Lang } from "@/lib/types";

export const COPY: Record<Lang, DashboardCopy> = {
  en: {
    title: "Hebbian Pattern Recall",
    subtitle: "Interactive Noisy Pattern Recall Using Hebbian Learning",
    description:
      "This system stores 10x10 bipolar patterns in a Hopfield-style autoassociative memory using the Hebbian learning rule. Corrupt any stored pattern with noise or masking, then observe the network reconstruct the original through iterative recall.",
    controls: "Controls",
    language: "Language",
    inputMode: "Input Mode",
    storedPattern: "Stored Pattern",
    drawCustom: "Draw Custom",
    pattern: "Pattern",
    corruption: "Corruption",
    noiseLevel: "Noise level",
    noiseHelp: "Fraction of cells randomly flipped",
    maskRatio: "Masking ratio",
    maskHelp: "Fraction of cells zeroed out (unknown)",
    recallSettings: "Recall",
    updateMode: "Update mode",
    synchronous: "Synchronous",
    asynchronous: "Asynchronous",
    maxRecallSteps: "Max steps",
    activationThreshold: "Threshold",
    randomSeed: "Seed",
    runRecall: "Run Recall",
    running: "Running recall...",
    clearGrid: "Clear",
    fillGrid: "Fill All",
    drawTitle: "Draw Your Pattern",
    drawHelp:
      "Toggle cells to set the custom input. Active cells are +1, inactive cells are -1.",
    storedPatterns: "Stored Patterns",
    result: "Recall Result",
    accuracy: "Accuracy",
    errors: "Bit Errors",
    overlap: "Overlap",
    nearestPattern: "Nearest",
    recallTrajectory: "Recall Trajectory",
    overlapAll: "Overlap with All Patterns",
    howItWorks: "How It Works",
    emptyState: "Run recall to see the original, corrupted, and reconstructed patterns.",
    galleryLoading: "Loading stored patterns...",
    galleryError: "Stored patterns could not be loaded.",
    recallError: "Recall request failed. Check the Vercel Python endpoint.",
    success: "Correct recall",
    failure: "Recall failed",
    explanation: [
      "Hebbian autoassociative memory stores each bipolar pattern as a stable attractor of a recurrent neural network.",
      "The weight matrix is built from outer products of the stored patterns and its diagonal is cleared to avoid self-reinforcement.",
      "During recall, the network iteratively updates each cell until the state converges. Noise flips cells, masking removes information, and the network fills in the missing structure from learned correlations.",
    ],
    convergedLabel: (steps: number) => `Converged in ${steps} step(s)`,
    energyLabel: (value: number) => `Energy: ${value.toFixed(2)}`,
  },
  tr: {
    title: "Hebbian Oruntu Hatirlama",
    subtitle: "Hebbian Ogrenme ile Etkilesimli Gurultulu Oruntu Hatirlama",
    description:
      "Bu sistem, Hebbian ogrenme kurali ile kurulmus Hopfield tipi bir otocagrisimli bellekte 10x10 bipolar oruntuler saklar. Saklanan bir oruntuyu gurultu veya maskeleme ile bozup agin iteratif hatirlama ile onu nasil yeniden kurdugunu gorebilirsiniz.",
    controls: "Kontroller",
    language: "Dil",
    inputMode: "Girdi Modu",
    storedPattern: "Sakli Oruntu",
    drawCustom: "Ozel Ciz",
    pattern: "Oruntu",
    corruption: "Bozma",
    noiseLevel: "Gurultu seviyesi",
    noiseHelp: "Rastgele cevrilen hucre orani",
    maskRatio: "Maskeleme orani",
    maskHelp: "Sifirlanan bilinmeyen hucre orani",
    recallSettings: "Hatirlama",
    updateMode: "Guncelleme modu",
    synchronous: "Eszamanli",
    asynchronous: "Eszamansiz",
    maxRecallSteps: "Maks adim",
    activationThreshold: "Esik",
    randomSeed: "Tohum",
    runRecall: "Hatirla",
    running: "Hatirlama calisiyor...",
    clearGrid: "Temizle",
    fillGrid: "Tumunu Doldur",
    drawTitle: "Oruntuyu Cizin",
    drawHelp:
      "Ozel girdiyi ayarlamak icin hucreleri degistirin. Aktif hucreler +1, pasif hucreler -1 olur.",
    storedPatterns: "Sakli Oruntuler",
    result: "Hatirlama Sonucu",
    accuracy: "Dogruluk",
    errors: "Bit Hatasi",
    overlap: "Ortusme",
    nearestPattern: "En Yakin",
    recallTrajectory: "Hatirlama Yorungesi",
    overlapAll: "Tum Oruntulerle Ortusme",
    howItWorks: "Nasil Calisiyor?",
    emptyState:
      "Orijinal, bozulmus ve yeniden kurulan oruntuleri gormek icin hatirlatmayi calistirin.",
    galleryLoading: "Sakli oruntuler yukleniyor...",
    galleryError: "Sakli oruntuler yuklenemedi.",
    recallError: "Hatirlama istegi basarisiz oldu. Vercel Python endpointini kontrol edin.",
    success: "Dogru hatirlama",
    failure: "Hatirlama basarisiz",
    explanation: [
      "Hebbian otocagrisimli bellek, bipolar oruntuleri tekrarlayan bir sinir aginda karali cekiciler olarak saklar.",
      "Agirlik matrisi, sakli oruntulerin dis carpimlarindan olusturulur ve kendini guclendirmeyi onlemek icin diyagonali sifirlanir.",
      "Hatirlama sirasinda ag hucreleri yinelemeli olarak gunceller ve durum yakinsayana kadar devam eder. Gurultu hucreleri cevirir, maskeleme bilgiyi siler, ag da ogrenilen korelasyonlarla eksik yapuyu tamamlar.",
    ],
    convergedLabel: (steps: number) => `${steps} adimda yakinsadi`,
    energyLabel: (value: number) => `Enerji: ${value.toFixed(2)}`,
  },
};
